package gotypegen

import (
	_ "embed"
	"fmt"
	"go/ast"
	"go/token"
	"path/filepath"
	"strconv"
	"strings"
)

//go:embed swift_prelude.swift
var swiftPrelude string

// GenerateSwift generates Swift Codable types.
//
// Mapping:
//   - struct               → public struct ... : Codable (public init, CodingKeys keep the JSON names)
//   - struct on a reference cycle (A → *B → *A) → public final class, since Swift value types cannot recurse
//   - `type X string` / int → RawRepresentable struct with `static let` members for every const of that type
//     (open enum: unknown wire values still decode)
//   - other aliases        → public typealias
//   - any / interface{} / json.RawMessage → JSONValue (from the prelude; see swift_prelude in config)
//   - pointer, omitempty, slice, map → Optional (nil slices/maps encode as null in Go)
//   - tstype:",extends" and inline embeds are flattened onto the child
func (g *PackageGenerator) GenerateSwift() (string, error) {
	w := &swiftWriter{g: g}
	if g.conf.IsTraceMode() {
		w.included = g.TraceTypes(g.BuildTypeGraph())
	}
	return w.generate()
}

type swiftWriter struct {
	g        *PackageGenerator
	included map[string]bool // nil → emit everything

	stringAliases map[string]bool
	intAliases    map[string]bool
	aliasTargets  map[string]string // typealias name → target ident (for cycle detection)
	structs       map[string]*ast.StructType
	expanded      map[string][]*ast.Field // struct name → fields after embed expansion
	classes       map[string]bool         // structs emitted as final class
	inlineLocal   map[string]bool         // local names of inline packages
	typeParams    map[string]bool         // active generic params while writing a struct

	members map[string][]swiftMember // enum type → consts
	types   []swiftTypeEntry
	loose   []swiftLooseConst
}

type swiftTypeEntry struct {
	spec *ast.TypeSpec
	doc  string
	file string
}

type swiftMember struct {
	name  string
	value string
	doc   string
}

type swiftLooseConst struct {
	name  string
	value string
	doc   string
}

type swiftField struct {
	jsonName string
	name     string
	typ      string
	optional bool
	doc      string
	tags     map[string]string
}

func (w *swiftWriter) generate() (string, error) {
	w.collect()
	w.detectCycles()

	s := new(strings.Builder)
	if w.g.conf.EmitSwiftPrelude() {
		s.WriteString(swiftPrelude)
	} else {
		s.WriteString("// Code generated by gotypegen. DO NOT EDIT.\n\nimport Foundation\n\n")
	}

	lastFile := ""
	for _, e := range w.types {
		if e.file != lastFile {
			fmt.Fprintf(s, "// MARK: - %s\n\n", filepath.Base(e.file))
			lastFile = e.file
		}
		w.writeType(s, e)
	}
	if len(w.loose) > 0 {
		s.WriteString("// MARK: - Constants\n\n")
		for _, c := range w.loose {
			writeSwiftDoc(s, c.doc, "")
			fmt.Fprintf(s, "public let %s = %s\n", c.name, c.value)
		}
		s.WriteString("\n")
	}
	return s.String(), nil
}

// rawType returns "String" or "Int" for enum-backed aliases, "" otherwise.
func (w *swiftWriter) rawType(name string) string {
	switch {
	case w.stringAliases[name]:
		return "String"
	case w.intAliases[name]:
		return "Int"
	}
	return ""
}

// collect walks the package once: aliases, types, const groups.
func (w *swiftWriter) collect() {
	g := w.g
	w.stringAliases, w.intAliases = g.collectScalarAliases()
	w.aliasTargets = map[string]string{}
	w.structs = map[string]*ast.StructType{}
	w.expanded = map[string][]*ast.Field{}
	w.classes = map[string]bool{}
	w.members = map[string][]swiftMember{}
	w.inlineLocal = g.buildInlineLocalNames()

	// Pass 1: struct and alias index (needed for embeds, cycles and consts).
	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok || gd.Tok != token.TYPE {
				continue
			}
			for _, spec := range gd.Specs {
				ts, ok := spec.(*ast.TypeSpec)
				if !ok || !ts.Name.IsExported() {
					continue
				}
				switch t := ts.Type.(type) {
				case *ast.Ident:
					if !isBuiltinType(t.Name) && t.Name != "any" {
						w.aliasTargets[ts.Name.Name] = t.Name
					}
				case *ast.StructType:
					w.structs[ts.Name.Name] = t
				}
			}
		}
	}

	// Pass 2: entries.
	seen := map[string]bool{}
	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}
		filename := g.GoFiles[i]
		for _, decl := range file.Decls {
			gd, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}
			switch gd.Tok {
			case token.TYPE:
				for _, spec := range gd.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() || !w.isIncluded(ts.Name.Name) || seen[ts.Name.Name] {
						continue
					}
					seen[ts.Name.Name] = true
					w.types = append(w.types, swiftTypeEntry{spec: ts, doc: specDoc(ts, gd), file: filename})
				}
			case token.CONST:
				w.collectConsts(gd)
			}
		}
	}
}

func (w *swiftWriter) isIncluded(name string) bool {
	return w.included == nil || w.included[name]
}

// fields returns a struct's fields with inline embeds and extends parents
// flattened, computed once per struct.
func (w *swiftWriter) fields(name string, st *ast.StructType) []*ast.Field {
	if f, ok := w.expanded[name]; ok {
		return f
	}
	var f []*ast.Field
	if st.Fields != nil {
		f = w.g.expandAllEmbeds(st.Fields.List)
	}
	w.expanded[name] = f
	return f
}

// collectConsts classifies each const: a member of a string/int alias type
// (→ static let on that type) or a loose literal (→ public let, all mode only).
func (w *swiftWriter) collectConsts(gd *ast.GenDecl) {
	var curType ast.Expr
	iota := -1
	for _, spec := range gd.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}
		iota++
		if vs.Type != nil {
			curType = vs.Type
		} else if len(vs.Values) > 0 {
			curType = nil // untyped const
		}
		doc := ""
		if vs.Doc != nil {
			doc = strings.TrimSpace(vs.Doc.Text())
		} else if vs.Comment != nil {
			doc = strings.TrimSpace(vs.Comment.Text())
		}

		typeName := ""
		if ident, ok := curType.(*ast.Ident); ok && w.rawType(ident.Name) != "" {
			typeName = ident.Name
		}

		for i, name := range vs.Names {
			if name.Name == "_" || !name.IsExported() {
				continue
			}
			var valueExpr ast.Expr
			if i < len(vs.Values) {
				valueExpr = vs.Values[i]
			}

			if typeName != "" {
				if !w.isIncluded(typeName) {
					continue
				}
				if value := w.constValue(valueExpr, iota, typeName); value != "" {
					w.members[typeName] = append(w.members[typeName], swiftMember{
						name:  swiftMemberName(name.Name, typeName),
						value: value,
						doc:   doc,
					})
				}
				continue
			}

			// Loose const: literal only, all mode only.
			if w.included != nil || valueExpr == nil {
				continue
			}
			if lit, ok := valueExpr.(*ast.BasicLit); ok {
				if v := swiftLiteral(lit); v != "" {
					w.loose = append(w.loose, swiftLooseConst{name: name.Name, value: v, doc: doc})
				}
			}
		}
	}
}

// constValue renders a const initializer as a Swift expression, or "" when it
// cannot be expressed (references to other packages, calls, …).
func (w *swiftWriter) constValue(expr ast.Expr, iota int, typeName string) string {
	if expr == nil {
		if w.rawType(typeName) == "Int" {
			return fmt.Sprintf("%d", iota)
		}
		return ""
	}
	switch v := expr.(type) {
	case *ast.BasicLit:
		return swiftLiteral(v)
	case *ast.Ident:
		if v.Name == "iota" {
			return fmt.Sprintf("%d", iota)
		}
		// Reference to a sibling member of the same type.
		want := swiftMemberName(v.Name, typeName)
		for _, m := range w.members[typeName] {
			if m.name == want {
				return fmt.Sprintf("%s.%s.rawValue", typeName, m.name)
			}
		}
		return ""
	case *ast.BinaryExpr:
		l := w.constValue(v.X, iota, typeName)
		r := w.constValue(v.Y, iota, typeName)
		if l == "" || r == "" {
			return ""
		}
		return fmt.Sprintf("%s %s %s", l, v.Op.String(), r)
	case *ast.UnaryExpr:
		x := w.constValue(v.X, iota, typeName)
		if x == "" {
			return ""
		}
		return v.Op.String() + x
	case *ast.ParenExpr:
		x := w.constValue(v.X, iota, typeName)
		if x == "" {
			return ""
		}
		return "(" + x + ")"
	case *ast.CallExpr:
		// Conversions like ToolType("x")
		if len(v.Args) == 1 {
			return w.constValue(v.Args[0], iota, typeName)
		}
	}
	return ""
}

// swiftLiteral converts a Go literal to a Swift literal.
func swiftLiteral(lit *ast.BasicLit) string {
	switch lit.Kind {
	case token.STRING:
		s, err := strconv.Unquote(lit.Value)
		if err != nil {
			return ""
		}
		return swiftQuote(s)
	case token.INT, token.FLOAT:
		return lit.Value
	}
	return "" // chars and imaginary literals have no scalar equivalent
}

// swiftQuote renders s as a Swift string literal.
func swiftQuote(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '\\':
			b.WriteString(`\\`)
		case '"':
			b.WriteString(`\"`)
		case '\n':
			b.WriteString(`\n`)
		case '\t':
			b.WriteString(`\t`)
		case '\r':
			b.WriteString(`\r`)
		case 0:
			b.WriteString(`\0`)
		default:
			if r < 0x20 || r == 0x7f {
				fmt.Fprintf(&b, `\u{%X}`, r)
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// swiftMemberName strips the type prefix and lowerCamels the rest:
// TaskStatusRunning (TaskStatus) → running; ScopeAgentsRead (Scope) → agentsRead.
func swiftMemberName(constName, typeName string) string {
	name := enumMemberBase(constName, typeName)
	if name == "" {
		name = constName
	}
	return swiftIdent(lowerCamel(name))
}

// detectCycles marks structs that can reach themselves through value or
// pointer fields (not through arrays or maps, which box their elements).
func (w *swiftWriter) detectCycles() {
	refs := map[string][]string{}
	for name, st := range w.structs {
		var out []string
		for _, f := range w.fields(name, st) {
			out = append(out, w.directRefs(f.Type)...)
		}
		refs[name] = out
	}
	for name := range w.structs {
		if w.reaches(name, name, refs, map[string]bool{}) {
			w.classes[name] = true
		}
	}
}

func (w *swiftWriter) directRefs(expr ast.Expr) []string {
	switch t := expr.(type) {
	case *ast.Ident:
		name := t.Name
		for i := 0; i < 8; i++ { // follow typealias chains
			target, ok := w.aliasTargets[name]
			if !ok {
				break
			}
			name = target
		}
		if _, ok := w.structs[name]; ok {
			return []string{name}
		}
	case *ast.StarExpr:
		return w.directRefs(t.X)
	case *ast.ParenExpr:
		return w.directRefs(t.X)
	case *ast.IndexExpr:
		return w.directRefs(t.X)
	case *ast.IndexListExpr:
		return w.directRefs(t.X)
	}
	return nil
}

func (w *swiftWriter) reaches(from, target string, refs map[string][]string, visited map[string]bool) bool {
	for _, r := range refs[from] {
		if r == target {
			return true
		}
		if visited[r] {
			continue
		}
		visited[r] = true
		if w.reaches(r, target, refs, visited) {
			return true
		}
	}
	return false
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

func (w *swiftWriter) writeType(s *strings.Builder, e swiftTypeEntry) {
	name := e.spec.Name.Name
	if raw := w.rawType(name); raw != "" {
		w.writeEnum(s, name, raw, e.doc)
		return
	}
	if st, ok := e.spec.Type.(*ast.StructType); ok {
		w.writeStruct(s, name, e.spec, st, e.doc)
		return
	}
	var typ string
	switch t := e.spec.Type.(type) {
	case *ast.StarExpr:
		inner, _ := w.typeOf(t.X)
		typ = inner + "?"
	case *ast.Ident, *ast.ArrayType, *ast.MapType, *ast.InterfaceType, *ast.SelectorExpr:
		typ, _ = w.typeOf(t)
	default:
		return // func, chan: nothing to express
	}
	writeSwiftDoc(s, e.doc, "")
	fmt.Fprintf(s, "public typealias %s = %s\n\n", name, typ)
}

func (w *swiftWriter) writeEnum(s *strings.Builder, name, raw, doc string) {
	writeSwiftDoc(s, doc, "")
	fmt.Fprintf(s, "public struct %s: RawRepresentable, Codable, Hashable, Sendable {\n", name)
	fmt.Fprintf(s, "    public let rawValue: %s\n", raw)
	fmt.Fprintf(s, "    public init(rawValue: %s) { self.rawValue = rawValue }\n", raw)
	members := w.members[name]
	if len(members) > 0 {
		s.WriteString("\n")
	}
	used := map[string]int{}
	for _, m := range members {
		mname := m.name
		if n := used[mname]; n > 0 {
			mname = fmt.Sprintf("%s%d", strings.Trim(mname, "`"), n+1)
		}
		used[m.name]++
		writeSwiftDoc(s, m.doc, "    ")
		fmt.Fprintf(s, "    public static let %s = %s(rawValue: %s)\n", mname, name, m.value)
	}
	s.WriteString("}\n\n")
}

func (w *swiftWriter) writeStruct(s *strings.Builder, name string, ts *ast.TypeSpec, st *ast.StructType, doc string) {
	generics := ""
	w.typeParams = map[string]bool{}
	if ts.TypeParams != nil {
		var names []string
		for _, f := range ts.TypeParams.List {
			for _, n := range f.Names {
				w.typeParams[n.Name] = true
				names = append(names, n.Name+": Codable")
			}
		}
		generics = "<" + strings.Join(names, ", ") + ">"
	}
	defer func() { w.typeParams = nil }()

	fields := w.collectFields(name, st)
	kind := "struct"
	if w.classes[name] {
		kind = "final class"
	}

	writeSwiftDoc(s, doc, "")
	fmt.Fprintf(s, "public %s %s%s: Codable {\n", kind, name, generics)

	for _, f := range fields {
		writeSwiftDoc(s, f.doc, "    ")
		fmt.Fprintf(s, "    public var %s: %s%s\n", f.name, f.typ, optMark(f.optional))
	}

	if len(fields) == 0 {
		s.WriteString("    public init() {}\n")
	} else {
		s.WriteString("\n    public init(\n")
		for i, f := range fields {
			sep := ","
			if i == len(fields)-1 {
				sep = ""
			}
			def := ""
			if f.optional {
				def = " = nil"
			} else if zv := swiftZeroValue(f.typ); zv != "" {
				def = " = " + zv // Go zero value; the server treats it as unset
			}
			fmt.Fprintf(s, "        %s: %s%s%s%s\n", f.name, f.typ, optMark(f.optional), def, sep)
		}
		s.WriteString("    ) {\n")
		for _, f := range fields {
			fmt.Fprintf(s, "        self.%s = %s\n", f.name, f.name)
		}
		s.WriteString("    }\n")

		s.WriteString("\n    enum CodingKeys: String, CodingKey {\n")
		for _, f := range fields {
			fmt.Fprintf(s, "        case %s = %q\n", f.name, f.jsonName)
		}
		s.WriteString("    }\n")
	}

	w.writeFieldTags(s, fields)
	s.WriteString("}\n\n")
}

func (w *swiftWriter) writeFieldTags(s *strings.Builder, fields []swiftField) {
	has := false
	for _, f := range fields {
		if len(f.tags) > 0 {
			has = true
			break
		}
	}
	if !has {
		return
	}
	s.WriteString("\n    public static let fieldTags: [String: [String: String]] = [\n")
	for _, f := range fields {
		if len(f.tags) == 0 {
			continue
		}
		var parts []string
		for _, k := range w.g.conf.FieldTags {
			if v, ok := f.tags[k]; ok {
				parts = append(parts, fmt.Sprintf("%q: %q", k, v))
			}
		}
		fmt.Fprintf(s, "        %q: [%s],\n", f.jsonName, strings.Join(parts, ", "))
	}
	s.WriteString("    ]\n")
}

func (w *swiftWriter) collectFields(structName string, st *ast.StructType) []swiftField {
	var out []swiftField
	usedNames := map[string]bool{}
	for _, field := range w.fields(structName, st) {
		names := field.Names
		if len(names) == 0 {
			// Anonymous field that survived expansion: json-named embed, or an
			// unresolvable/foreign type. Keep only the json-named case.
			if w.g.isInlineEmbed(field) || w.g.isExtendsEmbed(field) {
				continue
			}
			typeName, ok := getAnonymousFieldName(field.Type)
			if !ok {
				continue
			}
			if jsonName, _ := w.g.getPyFieldInfo(field); jsonName == "" || jsonName == "-" {
				continue
			}
			names = []*ast.Ident{ast.NewIdent(typeName)}
		}
		for _, ident := range names {
			if !ident.IsExported() {
				continue
			}
			jsonName, omitempty := w.g.getPyFieldInfo(field)
			if jsonName == "-" {
				continue
			}
			if jsonName == "" {
				jsonName = ident.Name
			}
			name := swiftIdent(lowerCamel(jsonName))
			for usedNames[name] {
				name = strings.Trim(name, "`") + "_"
			}
			usedNames[name] = true

			typ, nullable := w.typeOf(field.Type)

			doc := ""
			if field.Doc != nil {
				doc = strings.TrimSpace(field.Doc.Text())
			} else if field.Comment != nil {
				doc = strings.TrimSpace(field.Comment.Text())
			}

			out = append(out, swiftField{
				jsonName: jsonName,
				name:     name,
				typ:      typ,
				optional: nullable || omitempty,
				doc:      doc,
				tags:     w.g.configuredFieldTags(field),
			})
		}
	}
	return out
}

// typeOf maps a Go type expression to (Swift type, nullable-on-the-wire).
func (w *swiftWriter) typeOf(expr ast.Expr) (string, bool) {
	switch t := expr.(type) {
	case *ast.Ident:
		return w.identType(t.Name), false
	case *ast.SelectorExpr:
		full := fmt.Sprintf("%s.%s", t.X, t.Sel.Name)
		if m, ok := w.g.conf.TypeMappings[full]; ok {
			return tsMappingToSwift(m)
		}
		if full == "time.Time" {
			return "String", false // RFC3339 on the wire
		}
		if x, ok := t.X.(*ast.Ident); ok && w.inlineLocal[x.Name] {
			return t.Sel.Name, false
		}
		return "JSONValue", false
	case *ast.StarExpr:
		typ, _ := w.typeOf(t.X)
		return typ, true
	case *ast.ParenExpr:
		return w.typeOf(t.X)
	case *ast.ArrayType:
		if ident, ok := t.Elt.(*ast.Ident); ok && (ident.Name == "byte" || ident.Name == "uint8") {
			if m, ok := w.g.conf.TypeMappings["[]byte"]; ok {
				typ, _ := tsMappingToSwift(m)
				return typ, true
			}
			return "Data", true
		}
		typ, _ := w.typeOf(t.Elt)
		return "[" + typ + "]", true
	case *ast.MapType:
		key, _ := w.typeOf(t.Key)
		if key != "Int" {
			key = "String" // Codable only round-trips String/Int keys as JSON objects
		}
		val, _ := w.typeOf(t.Value)
		return "[" + key + ": " + val + "]", true
	case *ast.IndexExpr:
		base, _ := w.typeOf(t.X)
		arg, _ := w.typeOf(t.Index)
		return base + "<" + arg + ">", false
	case *ast.IndexListExpr:
		base, _ := w.typeOf(t.X)
		var args []string
		for _, ix := range t.Indices {
			a, _ := w.typeOf(ix)
			args = append(args, a)
		}
		return base + "<" + strings.Join(args, ", ") + ">", false
	case *ast.InterfaceType:
		return "JSONValue", false
	case *ast.StructType:
		return "[String: JSONValue]", false
	}
	return "JSONValue", false
}

func (w *swiftWriter) identType(name string) string {
	if w.typeParams[name] {
		return name
	}
	if m, ok := w.g.conf.TypeMappings[name]; ok {
		typ, _ := tsMappingToSwift(m)
		return typ
	}
	switch name {
	case "string":
		return "String"
	case "bool":
		return "Bool"
	case "float32", "float64":
		return "Double"
	case "any", "interface{}", "error":
		return "JSONValue"
	}
	if isGoIntType(name) || name == "byte" || name == "rune" {
		return "Int"
	}
	if len(name) == 1 && name[0] >= 'A' && name[0] <= 'Z' {
		return "JSONValue" // stray generic param
	}
	if name == "" || !ast.IsExported(name) {
		return "JSONValue"
	}
	return name
}

func tsMappingToSwift(mapping string) (string, bool) {
	base, _, nullable := parseTypeMappingForSchema(mapping)
	switch strings.TrimSpace(base) {
	case "string":
		return "String", nullable
	case "number":
		return "Double", nullable
	case "boolean":
		return "Bool", nullable
	}
	return "JSONValue", nullable
}

// ---------------------------------------------------------------------------
// Naming helpers
// ---------------------------------------------------------------------------

// lowerCamel: "chat_id" → "chatId", "io.modelcontextprotocol/serverInfo" → "ioModelcontextprotocolServerInfo",
// "ID" → "id", "URL" → "url", "HTTPServer" → "httpServer", "ttlMs" → "ttlMs".
func lowerCamel(s string) string {
	var parts []string
	var cur strings.Builder
	flush := func() {
		if cur.Len() > 0 {
			parts = append(parts, cur.String())
			cur.Reset()
		}
	}
	for _, r := range s {
		if r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || r >= '0' && r <= '9' {
			cur.WriteRune(r)
		} else {
			flush()
		}
	}
	flush()
	if len(parts) == 0 {
		return "value"
	}
	var b strings.Builder
	for i, p := range parts {
		if i == 0 {
			b.WriteString(lowerFirstWord(p))
		} else {
			b.WriteString(strings.ToUpper(p[:1]) + p[1:])
		}
	}
	out := b.String()
	if out[0] >= '0' && out[0] <= '9' {
		out = "_" + out
	}
	return out
}

// lowerFirstWord lowercases the leading acronym/word: "ID"→"id", "HTTPServer"→"httpServer", "Name"→"name".
func lowerFirstWord(p string) string {
	runes := []rune(p)
	n := 0
	for n < len(runes) && runes[n] >= 'A' && runes[n] <= 'Z' {
		n++
	}
	switch {
	case n == 0:
		return p
	case n == len(runes):
		return strings.ToLower(p)
	case n == 1:
		return strings.ToLower(string(runes[0])) + string(runes[1:])
	}
	// acronym followed by a word: keep the last capital as the word start
	return strings.ToLower(string(runes[:n-1])) + string(runes[n-1:])
}

var swiftKeywords = map[string]bool{
	"associatedtype": true, "class": true, "deinit": true, "enum": true, "extension": true,
	"fileprivate": true, "func": true, "import": true, "init": true, "inout": true,
	"internal": true, "let": true, "open": true, "operator": true, "private": true,
	"precedencegroup": true, "protocol": true, "public": true, "rethrows": true,
	"static": true, "struct": true, "subscript": true, "typealias": true, "var": true,
	"break": true, "case": true, "catch": true, "continue": true, "default": true,
	"defer": true, "do": true, "else": true, "fallthrough": true, "for": true,
	"guard": true, "if": true, "in": true, "repeat": true, "return": true, "throw": true,
	"switch": true, "where": true, "while": true, "Any": true, "as": true, "await": true,
	"false": true, "is": true, "nil": true, "self": true, "Self": true, "super": true,
	"throws": true, "true": true, "try": true, "Type": true, "Protocol": true,
}

func swiftIdent(name string) string {
	if swiftKeywords[name] {
		return "`" + name + "`"
	}
	return name
}

// swiftZeroValue gives scalar init defaults so request types are ergonomic
// (LLMInput(text: "hi")) while decoding still requires the field, which Go
// always emits for non-omitempty scalars.
func swiftZeroValue(typ string) string {
	switch typ {
	case "String":
		return `""`
	case "Int", "Double":
		return "0"
	case "Bool":
		return "false"
	case "JSONValue":
		return ".null"
	}
	return ""
}

func optMark(optional bool) string {
	if optional {
		return "?"
	}
	return ""
}

func writeSwiftDoc(s *strings.Builder, doc, indent string) {
	if doc == "" {
		return
	}
	for _, line := range strings.Split(doc, "\n") {
		s.WriteString(indent)
		s.WriteString("/// ")
		s.WriteString(line)
		s.WriteString("\n")
	}
}
