package gotypegen

import (
	"fmt"
	"go/ast"
	"go/token"
	"strings"

	"github.com/fatih/structtag"
)

// enumMemberInfo stores the Python enum type and member name for a Go const
type enumMemberInfo struct {
	typeName   string
	memberName string
}

// GeneratePython generates Python type definitions using TypedDict
func (g *PackageGenerator) GeneratePython() (string, error) {
	// Use traced generation if in trace mode
	if g.conf.IsTraceMode() {
		return g.GeneratePythonTraced()
	}

	s := new(strings.Builder)

	// Header and imports
	s.WriteString("# Code generated by gotypegen. DO NOT EDIT.\n\n")
	s.WriteString("from __future__ import annotations\n\n")
	s.WriteString("from enum import Enum, IntEnum\n")
	s.WriteString("from typing import Any, Dict, List, Optional, TypedDict, Union\n")
	s.WriteString("from datetime import datetime\n\n")

	// Track seen type names to skip duplicates
	seenTypes := make(map[string]bool)
	// Track string type aliases for StrEnum generation
	stringTypeAliases := make(map[string]bool)
	// Track int type aliases for IntEnum generation
	intTypeAliases := make(map[string]bool)

	// First pass: identify string and int type aliases
	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.IsExported() {
					if ident, ok := ts.Type.(*ast.Ident); ok {
						switch ident.Name {
						case "string":
							stringTypeAliases[ts.Name.Name] = true
						case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
							intTypeAliases[ts.Name.Name] = true
						}
					}
				}
			}
		}
	}

	// Second pass: build enum member map (Go const name -> Python enum reference)
	enumMembers := g.buildEnumMemberMap(stringTypeAliases, intTypeAliases)

	// Collect all type definitions
	var typeSpecs []typeSpecWithDoc

	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}

		// Write file source comment
		filename := g.GoFiles[i]
		parts := strings.Split(filename, "/")
		fileComment := fmt.Sprintf("\n##########\n# source: %s\n\n", parts[len(parts)-1])
		s.WriteString(fileComment)

		// Only process top-level declarations (not types inside functions)
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}

			if genDecl.Tok == token.TYPE {
				for _, spec := range genDecl.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.IsExported() {
						// Skip duplicate type names
						if seenTypes[ts.Name.Name] {
							continue
						}
						seenTypes[ts.Name.Name] = true

						// Skip string/int type aliases (they become enums with consts)
						if stringTypeAliases[ts.Name.Name] || intTypeAliases[ts.Name.Name] {
							continue
						}

						doc := ""
						if ts.Doc != nil {
							doc = strings.TrimSpace(ts.Doc.Text())
						} else if genDecl.Doc != nil {
							doc = strings.TrimSpace(genDecl.Doc.Text())
						}
						typeSpecs = append(typeSpecs, typeSpecWithDoc{ts, doc})
						g.writePyType(s, ts, doc)
					}
				}
			} else if genDecl.Tok == token.CONST {
				g.writePyConsts(s, genDecl, stringTypeAliases, intTypeAliases, enumMembers)
			}
		}
	}

	return s.String(), nil
}

// buildEnumMemberMap creates a mapping from Go const names to Python enum references
func (g *PackageGenerator) buildEnumMemberMap(stringTypeAliases, intTypeAliases map[string]bool) map[string]enumMemberInfo {
	enumMembers := make(map[string]enumMemberInfo)

	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.CONST {
				continue
			}

			// Find the type for this const group
			var groupTypeName string
			for _, spec := range genDecl.Specs {
				if vs, ok := spec.(*ast.ValueSpec); ok && vs.Type != nil {
					if ident, ok := vs.Type.(*ast.Ident); ok {
						if stringTypeAliases[ident.Name] || intTypeAliases[ident.Name] {
							groupTypeName = ident.Name
						}
					}
				}
				break
			}

			if groupTypeName == "" {
				continue
			}

			// Record all members of this enum
			for _, spec := range genDecl.Specs {
				vs, ok := spec.(*ast.ValueSpec)
				if !ok {
					continue
				}
				for _, name := range vs.Names {
					if name.Name == "_" || !name.IsExported() {
						continue
					}
					memberName := name.Name
					if strings.HasPrefix(memberName, groupTypeName) {
						memberName = memberName[len(groupTypeName):]
					}
					memberName = toUpperSnake(memberName)
					enumMembers[name.Name] = enumMemberInfo{groupTypeName, memberName}
				}
			}
		}
	}

	return enumMembers
}

// GeneratePythonTraced generates Python types with dependency tracing
func (g *PackageGenerator) GeneratePythonTraced() (string, error) {
	s := new(strings.Builder)

	// Header and imports
	s.WriteString("# Code generated by gotypegen. DO NOT EDIT.\n\n")
	s.WriteString("from __future__ import annotations\n\n")
	s.WriteString("from enum import Enum, IntEnum\n")
	s.WriteString("from typing import Any, Dict, List, Optional, TypedDict, Union\n")
	s.WriteString("from datetime import datetime\n\n")

	// Build type graph and trace dependencies
	graph := g.BuildTypeGraph()
	includedTypes := g.TraceTypes(graph)

	// Track seen type names to skip duplicates
	seenTypes := make(map[string]bool)
	writtenHeaders := make(map[string]bool)
	// Track string type aliases for StrEnum generation
	stringTypeAliases := make(map[string]bool)
	// Track int type aliases for IntEnum generation
	intTypeAliases := make(map[string]bool)

	// First pass: identify string and int type aliases
	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}
			for _, spec := range genDecl.Specs {
				if ts, ok := spec.(*ast.TypeSpec); ok && ts.Name.IsExported() {
					if ident, ok := ts.Type.(*ast.Ident); ok {
						switch ident.Name {
						case "string":
							stringTypeAliases[ts.Name.Name] = true
						case "int", "int8", "int16", "int32", "int64", "uint", "uint8", "uint16", "uint32", "uint64":
							intTypeAliases[ts.Name.Name] = true
						}
					}
				}
			}
		}
	}

	// Build enum member map (Go const name -> Python enum reference)
	enumMembers := g.buildEnumMemberMap(stringTypeAliases, intTypeAliases)

	for i, file := range g.pkg.Syntax {
		if g.conf.IsFileIgnored(g.GoFiles[i]) {
			continue
		}

		filename := g.GoFiles[i]
		wroteHeader := false

		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok {
				continue
			}

			if genDecl.Tok == token.TYPE {
				for _, spec := range genDecl.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}

					// Only emit if this type is included
					if !includedTypes[ts.Name.Name] {
						continue
					}

					// Skip duplicate type names
					if seenTypes[ts.Name.Name] {
						continue
					}
					seenTypes[ts.Name.Name] = true

					// Skip string/int type aliases (they become enums with consts)
					if stringTypeAliases[ts.Name.Name] || intTypeAliases[ts.Name.Name] {
						continue
					}

					// Write file header if not yet written
					if !wroteHeader {
						parts := strings.Split(filename, "/")
						fileComment := fmt.Sprintf("\n##########\n# source: %s\n\n", parts[len(parts)-1])
						s.WriteString(fileComment)
						wroteHeader = true
						writtenHeaders[filename] = true
					}

					doc := ""
					if ts.Doc != nil {
						doc = strings.TrimSpace(ts.Doc.Text())
					} else if genDecl.Doc != nil {
						doc = strings.TrimSpace(genDecl.Doc.Text())
					}
					g.writePyType(s, ts, doc)
				}
			} else if genDecl.Tok == token.CONST {
				// Check if any constants are for included types
				shouldEmit := false
				for _, spec := range genDecl.Specs {
					if vs, ok := spec.(*ast.ValueSpec); ok && vs.Type != nil {
						if ident, ok := vs.Type.(*ast.Ident); ok {
							if includedTypes[ident.Name] {
								shouldEmit = true
								break
							}
						}
					}
				}
				if shouldEmit {
					if !wroteHeader {
						parts := strings.Split(filename, "/")
						fileComment := fmt.Sprintf("\n##########\n# source: %s\n\n", parts[len(parts)-1])
						s.WriteString(fileComment)
						wroteHeader = true
						writtenHeaders[filename] = true
					}
					g.writePyConsts(s, genDecl, stringTypeAliases, intTypeAliases, enumMembers)
				}
			}
		}
	}

	return s.String(), nil
}

type typeSpecWithDoc struct {
	spec *ast.TypeSpec
	doc  string
}

func (g *PackageGenerator) writePyType(s *strings.Builder, ts *ast.TypeSpec, doc string) {
	switch t := ts.Type.(type) {
	case *ast.Ident:
		g.writePyTypeAlias(s, ts.Name.Name, t, doc)
	case *ast.StructType:
		g.writePyTypedDict(s, ts.Name.Name, t, doc)
	case *ast.ArrayType:
		g.writePyArrayAlias(s, ts.Name.Name, t, doc)
	case *ast.MapType:
		g.writePyMapAlias(s, ts.Name.Name, t, doc)
	}
}

func (g *PackageGenerator) writePyTypeAlias(s *strings.Builder, name string, ident *ast.Ident, doc string) {
	if doc != "" {
		s.WriteString("# ")
		s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
		s.WriteString("\n")
	}
	// Use base Go type directly (don't apply type mappings for type definitions)
	pyType := goBaseToPython(ident.Name)
	s.WriteString(name)
	s.WriteString(" = ")
	s.WriteString(pyType)
	s.WriteString("\n\n")
}

func (g *PackageGenerator) writePyArrayAlias(s *strings.Builder, name string, arr *ast.ArrayType, doc string) {
	if doc != "" {
		s.WriteString("# ")
		s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
		s.WriteString("\n")
	}
	s.WriteString(name)
	s.WriteString(" = ")
	s.WriteString(g.exprToPythonTypeQuoted(arr))
	s.WriteString("\n\n")
}

func (g *PackageGenerator) writePyMapAlias(s *strings.Builder, name string, m *ast.MapType, doc string) {
	if doc != "" {
		s.WriteString("# ")
		s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
		s.WriteString("\n")
	}
	s.WriteString(name)
	s.WriteString(" = ")
	s.WriteString(g.exprToPythonTypeQuoted(m))
	s.WriteString("\n\n")
}

func (g *PackageGenerator) writePyTypedDict(s *strings.Builder, name string, st *ast.StructType, doc string) {
	if doc != "" {
		s.WriteString("# ")
		s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
		s.WriteString("\n")
	}

	// Collect parent types from embedded fields with tstype:",extends"
	parents := g.collectPyParentTypes(st.Fields.List)

	s.WriteString("class ")
	s.WriteString(name)
	s.WriteString("(")
	for _, p := range parents {
		s.WriteString(p)
		s.WriteString(", ")
	}
	s.WriteString("TypedDict, total=False):\n")

	if st.Fields == nil || len(st.Fields.List) == 0 {
		s.WriteString("    pass\n\n")
		return
	}

	hasFields := false
	for _, field := range st.Fields.List {
		if len(field.Names) == 0 {
			continue // Skip embedded (inherited via class parents)
		}
		for _, fieldName := range field.Names {
			if !fieldName.IsExported() {
				continue
			}

			jsonName, _ := g.getPyFieldInfo(field)
			if jsonName == "-" {
				continue
			}
			if jsonName == "" {
				jsonName = fieldName.Name
			}

			hasFields = true

			if field.Doc != nil {
				fieldDoc := strings.TrimSpace(field.Doc.Text())
				s.WriteString("    # ")
				s.WriteString(strings.ReplaceAll(fieldDoc, "\n", "\n    # "))
				s.WriteString("\n")
			}

			s.WriteString("    ")
			pyFieldName := jsonName
			if isPythonKeyword(jsonName) {
				pyFieldName = jsonName + "_"
			}
			s.WriteString(pyFieldName)
			s.WriteString(": ")

			pyType := g.exprToPythonType(field.Type)
			s.WriteString(pyType)
			s.WriteString("\n")
		}
	}

	if !hasFields {
		s.WriteString("    pass\n")
	}
	s.WriteString("\n")
}

// collectPyParentTypes extracts parent type names from embedded fields
// that have a tstype:",extends" tag, mirroring the TypeScript inheritance behavior.
func (g *PackageGenerator) collectPyParentTypes(fields []*ast.Field) []string {
	var parents []string
	for _, f := range fields {
		if f.Type == nil || f.Tag == nil {
			continue
		}
		tags, err := structtag.Parse(f.Tag.Value[1 : len(f.Tag.Value)-1])
		if err != nil {
			continue
		}
		tstypeTag, err := tags.Get("tstype")
		if err != nil || !tstypeTag.HasOption("extends") {
			continue
		}
		name, valid := getAnonymousFieldName(f.Type)
		if valid {
			parents = append(parents, name)
		}
	}
	return parents
}

func (g *PackageGenerator) writePyConsts(s *strings.Builder, decl *ast.GenDecl, stringTypeAliases, intTypeAliases map[string]bool, enumMembers map[string]enumMemberInfo) {
	if decl.Doc != nil {
		doc := strings.TrimSpace(decl.Doc.Text())
		s.WriteString("# ")
		s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
		s.WriteString("\n")
	}

	iotaValue := -1
	var groupType string
	var groupTypeName string
	isStringEnum := false
	isIntEnum := false

	for _, spec := range decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok || vs.Type == nil {
			continue
		}
		if ident, ok := vs.Type.(*ast.Ident); ok {
			groupTypeName = ident.Name
			if stringTypeAliases[ident.Name] {
				isStringEnum = true
			} else if intTypeAliases[ident.Name] {
				isIntEnum = true
			}
			groupType = goBaseToPython(ident.Name)
		} else {
			groupType = g.exprToPythonType(vs.Type)
		}
		break
	}

	if isStringEnum {
		g.writePyStrEnum(s, decl, groupTypeName)
		return
	}

	if isIntEnum {
		g.writePyIntEnum(s, decl, groupTypeName)
		return
	}

	for _, spec := range decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		for i, name := range vs.Names {
			iotaValue++

			if name.Name == "_" {
				continue
			}
			if !name.IsExported() {
				continue
			}

			if vs.Doc != nil {
				doc := strings.TrimSpace(vs.Doc.Text())
				s.WriteString("# ")
				s.WriteString(strings.ReplaceAll(doc, "\n", "\n# "))
				s.WriteString("\n")
			}

			s.WriteString(name.Name)

			if groupType != "" {
				s.WriteString(": ")
				s.WriteString(groupType)
			}

			s.WriteString(" = ")

			if i < len(vs.Values) {
				s.WriteString(g.getPyConstValue(vs.Values[i], iotaValue, enumMembers))
			} else {
				s.WriteString(fmt.Sprintf("%d", iotaValue))
			}
			s.WriteString("\n")
		}
	}
	s.WriteString("\n")
}

func (g *PackageGenerator) writePyIntEnum(s *strings.Builder, decl *ast.GenDecl, typeName string) {
	s.WriteString("class ")
	s.WriteString(typeName)
	s.WriteString("(IntEnum):\n")

	hasMembers := false
	iotaValue := -1
	for _, spec := range decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		for i, name := range vs.Names {
			iotaValue++

			if name.Name == "_" || !name.IsExported() {
				continue
			}

			hasMembers = true

			if vs.Doc != nil {
				doc := strings.TrimSpace(vs.Doc.Text())
				s.WriteString("    # ")
				s.WriteString(strings.ReplaceAll(doc, "\n", "\n    # "))
				s.WriteString("\n")
			}

			memberName := name.Name
			if strings.HasPrefix(memberName, typeName) {
				memberName = memberName[len(typeName):]
			}
			memberName = toUpperSnake(memberName)

			s.WriteString("    ")
			s.WriteString(memberName)
			s.WriteString(" = ")

			if i < len(vs.Values) {
				s.WriteString(g.getPyConstValue(vs.Values[i], iotaValue, nil))
			} else {
				s.WriteString(fmt.Sprintf("%d", iotaValue))
			}
			s.WriteString("\n")
		}
	}

	if !hasMembers {
		s.WriteString("    pass\n")
	}
	s.WriteString("\n")
}

// writePyStrEnum generates a StrEnum class for string const groups.
// Uses (str, Enum) instead of StrEnum for Python 3.10 compatibility.
func (g *PackageGenerator) writePyStrEnum(s *strings.Builder, decl *ast.GenDecl, typeName string) {
	s.WriteString("class ")
	s.WriteString(typeName)
	s.WriteString("(str, Enum):\n")

	hasMembers := false
	for _, spec := range decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		for i, name := range vs.Names {
			if name.Name == "_" || !name.IsExported() {
				continue
			}

			hasMembers = true

			if vs.Doc != nil {
				doc := strings.TrimSpace(vs.Doc.Text())
				s.WriteString("    # ")
				s.WriteString(strings.ReplaceAll(doc, "\n", "\n    # "))
				s.WriteString("\n")
			}

			memberName := name.Name
			if strings.HasPrefix(memberName, typeName) {
				memberName = memberName[len(typeName):]
			}
			memberName = toUpperSnake(memberName)

			s.WriteString("    ")
			s.WriteString(memberName)
			s.WriteString(" = ")

			if i < len(vs.Values) {
				s.WriteString(g.getPyConstValue(vs.Values[i], 0, nil))
			} else {
				s.WriteString(`""`)
			}
			s.WriteString("\n")
		}
	}

	if !hasMembers {
		s.WriteString("    pass\n")
	}
	s.WriteString("\n")
}

// toUpperSnake converts CamelCase to UPPER_SNAKE_CASE
func toUpperSnake(s string) string {
	var result strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			result.WriteByte('_')
		}
		if r >= 'a' && r <= 'z' {
			result.WriteByte(byte(r - 'a' + 'A'))
		} else {
			result.WriteRune(r)
		}
	}
	name := result.String()
	if len(name) > 0 && name[0] >= '0' && name[0] <= '9' {
		name = "_" + name
	}
	return name
}

func (g *PackageGenerator) getPyConstValue(expr ast.Expr, iotaValue int, enumMembers map[string]enumMemberInfo) string {
	switch v := expr.(type) {
	case *ast.BasicLit:
		return v.Value
	case *ast.Ident:
		if v.Name == "iota" {
			return fmt.Sprintf("%d", iotaValue)
		}
		if info, ok := enumMembers[v.Name]; ok {
			return fmt.Sprintf("%s.%s", info.typeName, info.memberName)
		}
		return v.Name
	case *ast.BinaryExpr:
		left := g.getPyConstValue(v.X, iotaValue, enumMembers)
		right := g.getPyConstValue(v.Y, iotaValue, enumMembers)
		return fmt.Sprintf("%s %s %s", left, v.Op.String(), right)
	case *ast.UnaryExpr:
		val := g.getPyConstValue(v.X, iotaValue, enumMembers)
		return fmt.Sprintf("%s%s", v.Op.String(), val)
	case *ast.ParenExpr:
		val := g.getPyConstValue(v.X, iotaValue, enumMembers)
		return fmt.Sprintf("(%s)", val)
	default:
		return fmt.Sprintf("%d", iotaValue)
	}
}

func (g *PackageGenerator) exprToPythonTypeQuoted(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		pyType := g.goTypeToPython(t.Name)
		if pyType != "str" && pyType != "int" && pyType != "float" && pyType != "bool" && pyType != "Any" && pyType != "bytes" {
			return fmt.Sprintf("\"%s\"", pyType)
		}
		return pyType
	case *ast.SelectorExpr:
		typeName := fmt.Sprintf("%s.%s", t.X, t.Sel.Name)
		if mapped, ok := g.conf.TypeMappings[typeName]; ok {
			return g.tsMappingToPython(mapped)
		}
		return "Any"
	case *ast.StarExpr:
		inner := g.exprToPythonTypeQuoted(t.X)
		return fmt.Sprintf("Optional[%s]", inner)
	case *ast.ArrayType:
		if ident, ok := t.Elt.(*ast.Ident); ok && ident.Name == "byte" {
			return "bytes"
		}
		inner := g.exprToPythonTypeQuoted(t.Elt)
		return fmt.Sprintf("List[%s]", inner)
	case *ast.MapType:
		keyType := g.exprToPythonTypeQuoted(t.Key)
		valType := g.exprToPythonTypeQuoted(t.Value)
		return fmt.Sprintf("Dict[%s, %s]", keyType, valType)
	case *ast.InterfaceType:
		return "Any"
	case *ast.StructType:
		return "Dict[str, Any]"
	default:
		return "Any"
	}
}

func (g *PackageGenerator) exprToPythonType(expr ast.Expr) string {
	switch t := expr.(type) {
	case *ast.Ident:
		return g.goTypeToPython(t.Name)
	case *ast.SelectorExpr:
		typeName := fmt.Sprintf("%s.%s", t.X, t.Sel.Name)
		if mapped, ok := g.conf.TypeMappings[typeName]; ok {
			return g.tsMappingToPython(mapped)
		}
		return "Any"
	case *ast.StarExpr:
		inner := g.exprToPythonType(t.X)
		return fmt.Sprintf("Optional[%s]", inner)
	case *ast.ArrayType:
		if ident, ok := t.Elt.(*ast.Ident); ok && ident.Name == "byte" {
			return "bytes"
		}
		inner := g.exprToPythonType(t.Elt)
		return fmt.Sprintf("List[%s]", inner)
	case *ast.MapType:
		keyType := g.exprToPythonType(t.Key)
		valType := g.exprToPythonType(t.Value)
		return fmt.Sprintf("Dict[%s, %s]", keyType, valType)
	case *ast.InterfaceType:
		return "Any"
	case *ast.StructType:
		return "Dict[str, Any]"
	default:
		return "Any"
	}
}

func goBaseToPython(goType string) string {
	switch goType {
	case "string":
		return "str"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "float"
	case "bool":
		return "bool"
	case "any", "interface{}":
		return "Any"
	default:
		return goType
	}
}

func (g *PackageGenerator) goTypeToPython(goType string) string {
	if mapped, ok := g.conf.TypeMappings[goType]; ok {
		return g.tsMappingToPython(mapped)
	}

	switch goType {
	case "string":
		return "str"
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64":
		return "int"
	case "float32", "float64":
		return "float"
	case "bool":
		return "bool"
	case "any", "interface{}":
		return "Any"
	default:
		// Generic type parameters (single uppercase letter like T, K, V) -> Any
		if len(goType) == 1 && goType[0] >= 'A' && goType[0] <= 'Z' {
			return "Any"
		}
		return goType
	}
}

func (g *PackageGenerator) tsMappingToPython(mapping string) string {
	baseType, _, nullable := parseTypeMappingForSchema(mapping)

	var pyType string
	switch baseType {
	case "string":
		pyType = "str"
	case "number":
		pyType = "float"
	case "boolean":
		pyType = "bool"
	case "any":
		pyType = "Any"
	default:
		pyType = "Any"
	}

	if nullable {
		return fmt.Sprintf("Optional[%s]", pyType)
	}
	return pyType
}

var pythonKeywords = map[string]bool{
	"False": true, "None": true, "True": true, "and": true, "as": true,
	"assert": true, "async": true, "await": true, "break": true, "class": true,
	"continue": true, "def": true, "del": true, "elif": true, "else": true,
	"except": true, "finally": true, "for": true, "from": true, "global": true,
	"if": true, "import": true, "in": true, "is": true, "lambda": true,
	"nonlocal": true, "not": true, "or": true, "pass": true, "raise": true,
	"return": true, "try": true, "while": true, "with": true, "yield": true,
}

func isPythonKeyword(s string) bool {
	return pythonKeywords[s]
}

func (g *PackageGenerator) getPyFieldInfo(field *ast.Field) (name string, optional bool) {
	if field.Tag == nil {
		return "", false
	}

	tags, err := structtag.Parse(field.Tag.Value[1 : len(field.Tag.Value)-1])
	if err != nil {
		return "", false
	}

	if jsonTag, err := tags.Get("json"); err == nil {
		name = jsonTag.Name
		if name == "-" {
			return "-", false
		}
		optional = jsonTag.HasOption("omitempty")
		return
	}

	if yamlTag, err := tags.Get("yaml"); err == nil && yamlTag.Name != "-" {
		name = yamlTag.Name
		optional = yamlTag.HasOption("omitempty")
	}

	return
}
