package gotypegen

import (
	"fmt"
	"go/ast"
	"go/token"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
)

// GenerateGo generates Go source code output.
func (g *PackageGenerator) GenerateGo() (string, error) {
	if g.conf.IsTraceMode() {
		return g.GenerateGoTraced()
	}
	return g.generateGoAll()
}

// inlinePkgPaths returns a set of inline package paths for use with FilterMethods.
func (g *PackageGenerator) inlinePkgPaths() map[string]bool {
	if len(g.inlinePkgs) == 0 {
		return nil
	}
	paths := make(map[string]bool)
	for _, pkg := range g.inlinePkgs {
		if pkg.PkgPath != "" {
			paths[pkg.PkgPath] = true
		} else {
			paths[pkg.ID] = true
		}
	}
	return paths
}

// generateGoAll emits all types (non-trace mode).
func (g *PackageGenerator) generateGoAll() (string, error) {
	graph := g.BuildTypeGraph()

	// Also merge inline package types
	for _, inlinePkg := range g.inlinePkgs {
		inlineGen := &PackageGenerator{
			conf:    g.conf,
			GoFiles: inlinePkg.GoFiles,
			pkg:     inlinePkg,
		}
		inlineGraph := inlineGen.BuildTypeGraph()
		for name, info := range inlineGraph.Types {
			graph.Types[name] = info
		}
		for file, types := range inlineGraph.FileTypes {
			graph.FileTypes[file] = types
		}
		for typeName, methods := range inlineGraph.Methods {
			graph.Methods[typeName] = append(graph.Methods[typeName], methods...)
		}
	}

	// Include all exported types
	allTypes := make(map[string]bool)
	for name := range graph.Types {
		allTypes[name] = true
	}
	allMethods := FilterMethods(graph, allTypes, g.pkg.TypesInfo, g.pkg.Types.Scope(), g.inlinePkgPaths())

	s := new(strings.Builder)
	g.writeGoHeader(s)

	// Collect all imports needed across all files
	imports := newGoImportCollector()

	// Buffer the body so we can compute imports first
	body := new(strings.Builder)

	for i, file := range g.pkg.Syntax {
		fp := g.GoFiles[i]
		if g.conf.IsFileIgnored(fp) {
			continue
		}
		fileImports := buildImportMap(file)
		g.generateGoFile(body, file, fp, nil, allMethods, fileImports, imports)
	}

	// Process inline package files
	for _, inlinePkg := range g.inlinePkgs {
		inlineAllMethods := FilterMethods(graph, allTypes, inlinePkg.TypesInfo, inlinePkg.Types.Scope(), g.inlinePkgPaths())
		for i, file := range inlinePkg.Syntax {
			fp := inlinePkg.GoFiles[i]
			if g.conf.IsFileIgnored(fp) {
				continue
			}
			fileImports := buildImportMap(file)
			g.generateGoFile(body, file, fp, nil, inlineAllMethods, fileImports, imports)
		}
	}

	g.writeGoImports(s, imports)
	s.WriteString(body.String())

	return s.String(), nil
}

// GenerateGoTraced emits only traced types + their filtered methods.
func (g *PackageGenerator) GenerateGoTraced() (string, error) {
	graph := g.BuildTypeGraph()

	// Also build graphs for inline packages and merge their types
	for _, inlinePkg := range g.inlinePkgs {
		inlineGen := &PackageGenerator{
			conf:    g.conf,
			GoFiles: inlinePkg.GoFiles,
			pkg:     inlinePkg,
		}
		inlineGraph := inlineGen.BuildTypeGraph()
		for name, info := range inlineGraph.Types {
			graph.Types[name] = info
		}
		for file, types := range inlineGraph.FileTypes {
			graph.FileTypes[file] = types
		}
		for typeName, methods := range inlineGraph.Methods {
			graph.Methods[typeName] = append(graph.Methods[typeName], methods...)
		}
	}

	includedTypes := g.TraceTypes(graph)
	filteredMethods := FilterMethods(graph, includedTypes, g.pkg.TypesInfo, g.pkg.Types.Scope(), g.inlinePkgPaths())

	s := new(strings.Builder)
	g.writeGoHeader(s)

	imports := newGoImportCollector()
	body := new(strings.Builder)

	// Process main package files
	for i, file := range g.pkg.Syntax {
		fp := g.GoFiles[i]
		if g.conf.IsFileIgnored(fp) {
			continue
		}
		fileImports := buildImportMap(file)
		g.generateGoFile(body, file, fp, includedTypes, filteredMethods, fileImports, imports)
	}

	// Process inline package files
	for _, inlinePkg := range g.inlinePkgs {
		inlineFilteredMethods := FilterMethods(graph, includedTypes, inlinePkg.TypesInfo, inlinePkg.Types.Scope(), g.inlinePkgPaths())
		for i, file := range inlinePkg.Syntax {
			fp := inlinePkg.GoFiles[i]
			if g.conf.IsFileIgnored(fp) {
				continue
			}
			fileImports := buildImportMap(file)
			g.generateGoFile(body, file, fp, includedTypes, inlineFilteredMethods, fileImports, imports)
		}
	}

	g.writeGoImports(s, imports)
	s.WriteString(body.String())

	return s.String(), nil
}

// GenerateGoMod returns the contents of a go.mod file if go_module is configured.
func (g *PackageGenerator) GenerateGoMod() string {
	if g.conf.GoModule == "" {
		return ""
	}
	return fmt.Sprintf("module %s\n\ngo 1.21\n", g.conf.GoModule)
}

func (g *PackageGenerator) writeGoHeader(s *strings.Builder) {
	s.WriteString("// Code generated by gotypegen. DO NOT EDIT.\n\n")
	pkg := g.conf.GoPackage
	if pkg == "" {
		pkg = "types"
	}
	s.WriteString("package ")
	s.WriteString(pkg)
	s.WriteString("\n")
}

// goImportCollector tracks imports needed by generated code.
type goImportCollector struct {
	paths map[string]bool // import path -> needed
}

func newGoImportCollector() *goImportCollector {
	return &goImportCollector{paths: make(map[string]bool)}
}

func (c *goImportCollector) Add(path string) {
	c.paths[path] = true
}

func (g *PackageGenerator) writeGoImports(s *strings.Builder, imports *goImportCollector) {
	if len(imports.paths) == 0 {
		return
	}

	// Sort for deterministic output
	paths := make([]string, 0, len(imports.paths))
	for p := range imports.paths {
		paths = append(paths, p)
	}
	sort.Strings(paths)

	// Separate stdlib from third-party
	var stdPaths, extPaths []string
	for _, p := range paths {
		if isStdlib(p) {
			stdPaths = append(stdPaths, p)
		} else {
			extPaths = append(extPaths, p)
		}
	}

	s.WriteString("\nimport (\n")
	for _, p := range stdPaths {
		s.WriteString("\t\"")
		s.WriteString(p)
		s.WriteString("\"\n")
	}
	if len(stdPaths) > 0 && len(extPaths) > 0 {
		s.WriteString("\n")
	}
	for _, p := range extPaths {
		s.WriteString("\t\"")
		s.WriteString(p)
		s.WriteString("\"\n")
	}
	s.WriteString(")\n")
}

// generateGoFile processes a single source file and emits Go types, consts, and methods.
func (g *PackageGenerator) generateGoFile(
	s *strings.Builder,
	file *ast.File,
	fp string,
	includedTypes map[string]bool, // nil = emit all
	filteredMethods map[string][]*MethodInfo, // nil = no methods
	fileImports map[string]string,
	imports *goImportCollector,
) {
	wroteHeader := false
	writeHeader := func() {
		if !wroteHeader {
			s.WriteString("\n// --------------------\n// source: ")
			s.WriteString(filepath.Base(fp))
			s.WriteString("\n// --------------------\n")
			wroteHeader = true
		}
	}

	// Track which methods we've emitted for types in this file
	emittedMethodTypes := make(map[string]bool)

	for _, decl := range file.Decls {
		switch d := decl.(type) {
		case *ast.GenDecl:
			if d.Tok == token.IMPORT {
				continue
			}

			if d.Tok == token.CONST {
				if g.shouldEmitConstGroup(d, includedTypes) {
					writeHeader()
					g.writeGoConstGroup(s, d, fileImports, imports)
				}
				continue
			}

			if d.Tok == token.TYPE {
				for _, spec := range d.Specs {
					ts, ok := spec.(*ast.TypeSpec)
					if !ok || !ts.Name.IsExported() {
						continue
					}
					if includedTypes != nil && !includedTypes[ts.Name.Name] {
						continue
					}

					// Skip type aliases that become self-referential after inlining
					// e.g., `type MetaItemType = shared.MetaItemType` → `type MetaItemType = MetaItemType`
					if ts.Assign.IsValid() {
						if sel, ok := ts.Type.(*ast.SelectorExpr); ok {
							if ident, ok := sel.X.(*ast.Ident); ok && fileImports != nil {
								if path, exists := fileImports[ident.Name]; exists {
									if g.conf.IsInlinePackage(path) && sel.Sel.Name == ts.Name.Name {
										continue
									}
								}
							}
						}
					}

					writeHeader()

					doc := ts.Doc
					if doc == nil {
						doc = d.Doc
					}
					g.writeGoTypeDecl(s, ts, doc, fileImports, imports)

					// Emit methods for this type right after the type
					if filteredMethods != nil {
						if methods, ok := filteredMethods[ts.Name.Name]; ok {
							for _, m := range methods {
								s.WriteString("\n")
								g.writeGoMethod(s, m, fileImports, imports)
							}
							emittedMethodTypes[ts.Name.Name] = true
						}
					}
				}
				continue
			}

			if d.Tok == token.VAR {
				continue // skip var declarations in Go output
			}
		}
	}
}

// shouldEmitConstGroup checks if a const group should be emitted.
func (g *PackageGenerator) shouldEmitConstGroup(decl *ast.GenDecl, includedTypes map[string]bool) bool {
	if includedTypes == nil {
		// Emit all exported const groups
		for _, spec := range decl.Specs {
			if vs, ok := spec.(*ast.ValueSpec); ok {
				for _, name := range vs.Names {
					if name.IsExported() {
						return true
					}
				}
			}
		}
		return false
	}

	// In trace mode, emit only consts whose type is included
	var groupType string
	for _, spec := range decl.Specs {
		if vs, ok := spec.(*ast.ValueSpec); ok {
			if vs.Type != nil {
				if ident, ok := vs.Type.(*ast.Ident); ok {
					groupType = ident.Name
				}
			}
			if groupType != "" && includedTypes[groupType] {
				return true
			}
		}
	}
	return false
}

func (g *PackageGenerator) writeGoTypeDecl(
	s *strings.Builder,
	ts *ast.TypeSpec,
	doc *ast.CommentGroup,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	s.WriteString("\n")

	if doc != nil && g.PreserveTypeComments() {
		writeGoComment(s, doc, "")
	}

	s.WriteString("type ")
	s.WriteString(ts.Name.Name)

	// Generic type params
	if ts.TypeParams != nil {
		g.writeGoTypeParams(s, ts.TypeParams)
	}

	switch t := ts.Type.(type) {
	case *ast.StructType:
		s.WriteString(" struct {\n")
		g.writeGoStructFields(s, t, fileImports, imports)
		s.WriteString("}")

	case *ast.Ident:
		s.WriteString(" ")
		s.WriteString(t.Name)

	case *ast.SelectorExpr:
		s.WriteString(" ")
		g.writeGoExpr(s, t, fileImports, imports)

	case *ast.ArrayType:
		s.WriteString(" ")
		g.writeGoExpr(s, t, fileImports, imports)

	case *ast.MapType:
		s.WriteString(" ")
		g.writeGoExpr(s, t, fileImports, imports)

	case *ast.InterfaceType:
		s.WriteString(" interface {\n")
		g.writeGoInterfaceMethods(s, t, fileImports, imports)
		s.WriteString("}")

	default:
		// Fallback: write as-is
		s.WriteString(" ")
		g.writeGoExpr(s, ts.Type, fileImports, imports)
	}

	s.WriteString("\n")
}

func (g *PackageGenerator) writeGoTypeParams(s *strings.Builder, params *ast.FieldList) {
	s.WriteString("[")
	for i, field := range params.List {
		for j, name := range field.Names {
			s.WriteString(name.Name)
			s.WriteString(" ")
			g.writeGoExpr(s, field.Type, nil, nil)
			if i != len(params.List)-1 || j != len(field.Names)-1 {
				s.WriteString(", ")
			}
		}
	}
	s.WriteString("]")
}

func (g *PackageGenerator) writeGoStructFields(
	s *strings.Builder,
	st *ast.StructType,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	if st.Fields == nil {
		return
	}

	for _, field := range st.Fields.List {
		if field.Doc != nil && g.PreserveTypeComments() {
			writeGoComment(s, field.Doc, "\t")
		}

		s.WriteString("\t")

		if len(field.Names) == 0 {
			// Embedded field
			g.writeGoExpr(s, field.Type, fileImports, imports)
		} else {
			for i, name := range field.Names {
				if i > 0 {
					s.WriteString(", ")
				}
				s.WriteString(name.Name)
			}
			s.WriteString(" ")
			g.writeGoExpr(s, field.Type, fileImports, imports)
		}

		// Struct tags
		if field.Tag != nil {
			filtered := g.filterStructTag(field.Tag.Value)
			if filtered != "" {
				s.WriteString(" ")
				s.WriteString(filtered)
			}
		}

		if field.Comment != nil && g.PreserveTypeComments() {
			s.WriteString(" ")
			s.WriteString(strings.TrimSpace(field.Comment.List[0].Text))
		}

		s.WriteString("\n")
	}
}

// filterStructTag applies the keep_tags allowlist to a raw struct tag string.
// Returns the filtered tag including backticks, or empty string if nothing left.
func (g *PackageGenerator) filterStructTag(rawTag string) string {
	if len(g.conf.KeepTags) == 0 {
		return rawTag // no filtering
	}

	// Strip backticks
	inner := strings.Trim(rawTag, "`")
	if inner == "" {
		return ""
	}

	tag := reflect.StructTag(inner)

	var kept []string
	// Parse tag keys by walking the raw string
	for _, key := range extractTagKeys(inner) {
		if g.conf.ShouldKeepTag(key) {
			val := tag.Get(key)
			if val != "" {
				kept = append(kept, fmt.Sprintf(`%s:"%s"`, key, val))
			}
		}
	}

	if len(kept) == 0 {
		return ""
	}
	return "`" + strings.Join(kept, " ") + "`"
}

// extractTagKeys returns the tag keys from a struct tag string (without backticks).
func extractTagKeys(tag string) []string {
	var keys []string
	seen := make(map[string]bool)

	for tag != "" {
		tag = strings.TrimLeft(tag, " ")
		if tag == "" {
			break
		}

		// Find key
		i := 0
		for i < len(tag) && tag[i] != ':' && tag[i] != '"' && tag[i] != ' ' {
			i++
		}
		if i == 0 || i >= len(tag) || tag[i] != ':' {
			break
		}
		key := tag[:i]
		tag = tag[i+1:] // skip ':'

		if len(tag) == 0 || tag[0] != '"' {
			break
		}

		// Find end of quoted value
		tag = tag[1:] // skip opening quote
		j := 0
		for j < len(tag) {
			if tag[j] == '\\' {
				j += 2
				continue
			}
			if tag[j] == '"' {
				break
			}
			j++
		}
		if j >= len(tag) {
			break
		}
		tag = tag[j+1:] // skip closing quote

		if !seen[key] {
			keys = append(keys, key)
			seen[key] = true
		}
	}

	return keys
}

func (g *PackageGenerator) writeGoInterfaceMethods(
	s *strings.Builder,
	iface *ast.InterfaceType,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	if iface.Methods == nil {
		return
	}

	for _, method := range iface.Methods.List {
		s.WriteString("\t")
		if len(method.Names) > 0 {
			s.WriteString(method.Names[0].Name)
		}
		if ft, ok := method.Type.(*ast.FuncType); ok {
			g.writeGoFuncSignature(s, ft, fileImports, imports)
		} else {
			// Embedded interface
			g.writeGoExpr(s, method.Type, fileImports, imports)
		}
		s.WriteString("\n")
	}
}

func (g *PackageGenerator) writeGoConstGroup(
	s *strings.Builder,
	decl *ast.GenDecl,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	s.WriteString("\n")
	if decl.Doc != nil && g.PreserveTypeComments() {
		writeGoComment(s, decl.Doc, "")
	}

	if len(decl.Specs) == 1 {
		vs := decl.Specs[0].(*ast.ValueSpec)
		if len(vs.Names) == 1 && vs.Names[0].IsExported() {
			s.WriteString("const ")
			g.writeGoValueSpec(s, vs, fileImports, imports)
			s.WriteString("\n")
			return
		}
	}

	s.WriteString("const (\n")
	for _, spec := range decl.Specs {
		vs, ok := spec.(*ast.ValueSpec)
		if !ok {
			continue
		}

		if vs.Doc != nil && g.PreserveTypeComments() {
			writeGoComment(s, vs.Doc, "\t")
		}

		s.WriteString("\t")
		g.writeGoValueSpec(s, vs, fileImports, imports)
		s.WriteString("\n")
	}
	s.WriteString(")\n")
}

func (g *PackageGenerator) writeGoValueSpec(
	s *strings.Builder,
	vs *ast.ValueSpec,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	for i, name := range vs.Names {
		if i > 0 {
			s.WriteString(", ")
		}
		s.WriteString(name.Name)
	}

	if vs.Type != nil {
		s.WriteString(" ")
		g.writeGoExpr(s, vs.Type, fileImports, imports)
	}

	if len(vs.Values) > 0 {
		s.WriteString(" = ")
		for i, val := range vs.Values {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, val, fileImports, imports)
		}
	}
}

// writeGoMethod emits a method declaration.
func (g *PackageGenerator) writeGoMethod(
	s *strings.Builder,
	mi *MethodInfo,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	fn := mi.FuncDecl

	if fn.Doc != nil && g.PreserveTypeComments() {
		writeGoComment(s, fn.Doc, "")
	}

	s.WriteString("func ")

	// Receiver
	s.WriteString("(")
	recv := fn.Recv.List[0]
	if len(recv.Names) > 0 {
		s.WriteString(recv.Names[0].Name)
		s.WriteString(" ")
	}
	g.writeGoExpr(s, recv.Type, fileImports, imports)
	s.WriteString(") ")

	// Method name
	s.WriteString(fn.Name.Name)

	// Signature
	g.writeGoFuncSignature(s, fn.Type, fileImports, imports)

	// Body
	if fn.Body != nil {
		s.WriteString(" ")
		g.writeGoBlockStmt(s, fn.Body, fileImports, imports)
	}

	s.WriteString("\n")
}

func (g *PackageGenerator) writeGoFuncSignature(
	s *strings.Builder,
	ft *ast.FuncType,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	// Type params (generic methods)
	if ft.TypeParams != nil {
		g.writeGoTypeParams(s, ft.TypeParams)
	}

	// Params
	s.WriteString("(")
	if ft.Params != nil {
		g.writeGoFieldList(s, ft.Params, fileImports, imports)
	}
	s.WriteString(")")

	// Returns
	if ft.Results != nil {
		if len(ft.Results.List) == 1 && len(ft.Results.List[0].Names) == 0 {
			s.WriteString(" ")
			g.writeGoExpr(s, ft.Results.List[0].Type, fileImports, imports)
		} else {
			s.WriteString(" (")
			g.writeGoFieldList(s, ft.Results, fileImports, imports)
			s.WriteString(")")
		}
	}
}

func (g *PackageGenerator) writeGoFieldList(
	s *strings.Builder,
	fl *ast.FieldList,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	for i, field := range fl.List {
		if i > 0 {
			s.WriteString(", ")
		}
		for j, name := range field.Names {
			if j > 0 {
				s.WriteString(", ")
			}
			s.WriteString(name.Name)
		}
		if len(field.Names) > 0 {
			s.WriteString(" ")
		}
		g.writeGoExpr(s, field.Type, fileImports, imports)
	}
}

// writeGoExpr writes a Go expression. This handles type expressions and value expressions.
func (g *PackageGenerator) writeGoExpr(
	s *strings.Builder,
	expr ast.Expr,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	if expr == nil {
		return
	}

	switch t := expr.(type) {
	case *ast.Ident:
		s.WriteString(t.Name)

	case *ast.StarExpr:
		s.WriteString("*")
		g.writeGoExpr(s, t.X, fileImports, imports)

	case *ast.ArrayType:
		s.WriteString("[]")
		g.writeGoExpr(s, t.Elt, fileImports, imports)

	case *ast.Ellipsis:
		s.WriteString("...")
		g.writeGoExpr(s, t.Elt, fileImports, imports)

	case *ast.MapType:
		s.WriteString("map[")
		g.writeGoExpr(s, t.Key, fileImports, imports)
		s.WriteString("]")
		g.writeGoExpr(s, t.Value, fileImports, imports)

	case *ast.SelectorExpr:
		if ident, ok := t.X.(*ast.Ident); ok {
			// Check if this package is inlined — emit just the selector name
			if fileImports != nil {
				if path, exists := fileImports[ident.Name]; exists {
					if g.conf.IsInlinePackage(path) {
						s.WriteString(t.Sel.Name)
						return
					}
					// Register import for non-inlined packages
					if imports != nil {
						imports.Add(path)
					}
				}
			}
			s.WriteString(ident.Name)
		} else {
			g.writeGoExpr(s, t.X, fileImports, imports)
		}
		s.WriteString(".")
		s.WriteString(t.Sel.Name)

	case *ast.StructType:
		s.WriteString("struct {\n")
		g.writeGoStructFields(s, t, fileImports, imports)
		s.WriteString("}")

	case *ast.InterfaceType:
		s.WriteString("interface{")
		if t.Methods != nil && len(t.Methods.List) > 0 {
			s.WriteString("\n")
			g.writeGoInterfaceMethods(s, t, fileImports, imports)
		}
		s.WriteString("}")

	case *ast.FuncType:
		s.WriteString("func")
		g.writeGoFuncSignature(s, t, fileImports, imports)

	case *ast.ChanType:
		switch t.Dir {
		case ast.SEND:
			s.WriteString("chan<- ")
		case ast.RECV:
			s.WriteString("<-chan ")
		default:
			s.WriteString("chan ")
		}
		g.writeGoExpr(s, t.Value, fileImports, imports)

	case *ast.IndexExpr:
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString("[")
		g.writeGoExpr(s, t.Index, fileImports, imports)
		s.WriteString("]")

	case *ast.IndexListExpr:
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString("[")
		for i, idx := range t.Indices {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, idx, fileImports, imports)
		}
		s.WriteString("]")

	case *ast.BasicLit:
		s.WriteString(t.Value)

	case *ast.CompositeLit:
		if t.Type != nil {
			g.writeGoExpr(s, t.Type, fileImports, imports)
		}
		s.WriteString("{")
		for i, elt := range t.Elts {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, elt, fileImports, imports)
		}
		s.WriteString("}")

	case *ast.KeyValueExpr:
		g.writeGoExpr(s, t.Key, fileImports, imports)
		s.WriteString(": ")
		g.writeGoExpr(s, t.Value, fileImports, imports)

	case *ast.UnaryExpr:
		s.WriteString(t.Op.String())
		g.writeGoExpr(s, t.X, fileImports, imports)

	case *ast.BinaryExpr:
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString(" ")
		s.WriteString(t.Op.String())
		s.WriteString(" ")
		g.writeGoExpr(s, t.Y, fileImports, imports)

	case *ast.ParenExpr:
		s.WriteString("(")
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString(")")

	case *ast.CallExpr:
		g.writeGoExpr(s, t.Fun, fileImports, imports)
		s.WriteString("(")
		for i, arg := range t.Args {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, arg, fileImports, imports)
		}
		if t.Ellipsis.IsValid() {
			s.WriteString("...")
		}
		s.WriteString(")")

	case *ast.TypeAssertExpr:
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString(".(")
		if t.Type != nil {
			g.writeGoExpr(s, t.Type, fileImports, imports)
		} else {
			s.WriteString("type")
		}
		s.WriteString(")")

	case *ast.SliceExpr:
		g.writeGoExpr(s, t.X, fileImports, imports)
		s.WriteString("[")
		if t.Low != nil {
			g.writeGoExpr(s, t.Low, fileImports, imports)
		}
		s.WriteString(":")
		if t.High != nil {
			g.writeGoExpr(s, t.High, fileImports, imports)
		}
		if t.Slice3 {
			s.WriteString(":")
			if t.Max != nil {
				g.writeGoExpr(s, t.Max, fileImports, imports)
			}
		}
		s.WriteString("]")

	case *ast.FuncLit:
		g.writeGoExpr(s, t.Type, fileImports, imports)
		s.WriteString(" ")
		g.writeGoBlockStmt(s, t.Body, fileImports, imports)

	default:
		s.WriteString(fmt.Sprintf("/* unhandled expr: %T */", expr))
	}
}

// writeGoBlockStmt writes a block statement (method body).
// We use a simplified AST-to-source approach that handles the common cases.
func (g *PackageGenerator) writeGoBlockStmt(
	s *strings.Builder,
	block *ast.BlockStmt,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	s.WriteString("{\n")
	for _, stmt := range block.List {
		g.writeGoStmt(s, stmt, fileImports, imports, 1)
	}
	s.WriteString("}")
}

func (g *PackageGenerator) writeGoStmt(
	s *strings.Builder,
	stmt ast.Stmt,
	fileImports map[string]string,
	imports *goImportCollector,
	depth int,
) {
	indent := strings.Repeat("\t", depth)

	switch st := stmt.(type) {
	case *ast.ReturnStmt:
		s.WriteString(indent)
		s.WriteString("return")
		if len(st.Results) > 0 {
			s.WriteString(" ")
			for i, r := range st.Results {
				if i > 0 {
					s.WriteString(", ")
				}
				g.writeGoExpr(s, r, fileImports, imports)
			}
		}
		s.WriteString("\n")

	case *ast.AssignStmt:
		s.WriteString(indent)
		for i, lhs := range st.Lhs {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, lhs, fileImports, imports)
		}
		s.WriteString(" ")
		s.WriteString(st.Tok.String())
		s.WriteString(" ")
		for i, rhs := range st.Rhs {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, rhs, fileImports, imports)
		}
		s.WriteString("\n")

	case *ast.ExprStmt:
		s.WriteString(indent)
		g.writeGoExpr(s, st.X, fileImports, imports)
		s.WriteString("\n")

	case *ast.DeclStmt:
		s.WriteString(indent)
		if gd, ok := st.Decl.(*ast.GenDecl); ok {
			switch gd.Tok {
			case token.VAR:
				s.WriteString("var ")
				for _, spec := range gd.Specs {
					if vs, ok := spec.(*ast.ValueSpec); ok {
						g.writeGoValueSpec(s, vs, fileImports, imports)
					}
				}
			case token.TYPE:
				for _, spec := range gd.Specs {
					if ts, ok := spec.(*ast.TypeSpec); ok {
						s.WriteString("type ")
						s.WriteString(ts.Name.Name)
						s.WriteString(" ")
						g.writeGoExpr(s, ts.Type, fileImports, imports)
					}
				}
			case token.CONST:
				s.WriteString("const ")
				for _, spec := range gd.Specs {
					if vs, ok := spec.(*ast.ValueSpec); ok {
						g.writeGoValueSpec(s, vs, fileImports, imports)
					}
				}
			}
		}
		s.WriteString("\n")

	case *ast.IfStmt:
		s.WriteString(indent)
		s.WriteString("if ")
		if st.Init != nil {
			g.writeGoStmtInline(s, st.Init, fileImports, imports)
			s.WriteString("; ")
		}
		g.writeGoExpr(s, st.Cond, fileImports, imports)
		s.WriteString(" {\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}
		s.WriteString(indent)
		s.WriteString("}")
		if st.Else != nil {
			s.WriteString(" else ")
			if elseBlock, ok := st.Else.(*ast.BlockStmt); ok {
				s.WriteString("{\n")
				for _, inner := range elseBlock.List {
					g.writeGoStmt(s, inner, fileImports, imports, depth+1)
				}
				s.WriteString(indent)
				s.WriteString("}")
			} else {
				g.writeGoStmt(s, st.Else, fileImports, imports, 0)
				return // no newline, handled by recursive call
			}
		}
		s.WriteString("\n")

	case *ast.ForStmt:
		s.WriteString(indent)
		s.WriteString("for ")
		if st.Init != nil {
			g.writeGoStmtInline(s, st.Init, fileImports, imports)
			s.WriteString("; ")
		}
		if st.Cond != nil {
			g.writeGoExpr(s, st.Cond, fileImports, imports)
		}
		if st.Post != nil {
			s.WriteString("; ")
			g.writeGoStmtInline(s, st.Post, fileImports, imports)
		}
		s.WriteString(" {\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.RangeStmt:
		s.WriteString(indent)
		s.WriteString("for ")
		if st.Key != nil {
			g.writeGoExpr(s, st.Key, fileImports, imports)
			if st.Value != nil {
				s.WriteString(", ")
				g.writeGoExpr(s, st.Value, fileImports, imports)
			}
			s.WriteString(" ")
			s.WriteString(st.Tok.String())
			s.WriteString(" ")
		}
		s.WriteString("range ")
		g.writeGoExpr(s, st.X, fileImports, imports)
		s.WriteString(" {\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.SwitchStmt:
		s.WriteString(indent)
		s.WriteString("switch ")
		if st.Init != nil {
			g.writeGoStmtInline(s, st.Init, fileImports, imports)
			s.WriteString("; ")
		}
		if st.Tag != nil {
			g.writeGoExpr(s, st.Tag, fileImports, imports)
			s.WriteString(" ")
		}
		s.WriteString("{\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.TypeSwitchStmt:
		s.WriteString(indent)
		s.WriteString("switch ")
		if st.Init != nil {
			g.writeGoStmtInline(s, st.Init, fileImports, imports)
			s.WriteString("; ")
		}
		g.writeGoStmtInline(s, st.Assign, fileImports, imports)
		s.WriteString(" {\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.CaseClause:
		s.WriteString(indent)
		if st.List == nil {
			s.WriteString("default:\n")
		} else {
			s.WriteString("case ")
			for i, expr := range st.List {
				if i > 0 {
					s.WriteString(", ")
				}
				g.writeGoExpr(s, expr, fileImports, imports)
			}
			s.WriteString(":\n")
		}
		for _, inner := range st.Body {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}

	case *ast.BranchStmt:
		s.WriteString(indent)
		s.WriteString(st.Tok.String())
		if st.Label != nil {
			s.WriteString(" ")
			s.WriteString(st.Label.Name)
		}
		s.WriteString("\n")

	case *ast.IncDecStmt:
		s.WriteString(indent)
		g.writeGoExpr(s, st.X, fileImports, imports)
		s.WriteString(st.Tok.String())
		s.WriteString("\n")

	case *ast.BlockStmt:
		s.WriteString(indent)
		s.WriteString("{\n")
		for _, inner := range st.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.DeferStmt:
		s.WriteString(indent)
		s.WriteString("defer ")
		g.writeGoExpr(s, st.Call, fileImports, imports)
		s.WriteString("\n")

	case *ast.GoStmt:
		s.WriteString(indent)
		s.WriteString("go ")
		g.writeGoExpr(s, st.Call, fileImports, imports)
		s.WriteString("\n")

	case *ast.SendStmt:
		s.WriteString(indent)
		g.writeGoExpr(s, st.Chan, fileImports, imports)
		s.WriteString(" <- ")
		g.writeGoExpr(s, st.Value, fileImports, imports)
		s.WriteString("\n")

	case *ast.SelectStmt:
		s.WriteString(indent)
		s.WriteString("select {\n")
		for _, inner := range st.Body.List {
			g.writeGoStmt(s, inner, fileImports, imports, depth)
		}
		s.WriteString(indent)
		s.WriteString("}\n")

	case *ast.CommClause:
		s.WriteString(indent)
		if st.Comm == nil {
			s.WriteString("default:\n")
		} else {
			s.WriteString("case ")
			g.writeGoStmtInline(s, st.Comm, fileImports, imports)
			s.WriteString(":\n")
		}
		for _, inner := range st.Body {
			g.writeGoStmt(s, inner, fileImports, imports, depth+1)
		}

	case *ast.LabeledStmt:
		s.WriteString(st.Label.Name)
		s.WriteString(":\n")
		g.writeGoStmt(s, st.Stmt, fileImports, imports, depth)

	default:
		s.WriteString(indent)
		s.WriteString(fmt.Sprintf("/* unhandled stmt: %T */\n", stmt))
	}
}

// writeGoStmtInline writes a statement without leading indent or trailing newline,
// for use in init clauses of if/for/switch.
func (g *PackageGenerator) writeGoStmtInline(
	s *strings.Builder,
	stmt ast.Stmt,
	fileImports map[string]string,
	imports *goImportCollector,
) {
	switch st := stmt.(type) {
	case *ast.AssignStmt:
		for i, lhs := range st.Lhs {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, lhs, fileImports, imports)
		}
		s.WriteString(" ")
		s.WriteString(st.Tok.String())
		s.WriteString(" ")
		for i, rhs := range st.Rhs {
			if i > 0 {
				s.WriteString(", ")
			}
			g.writeGoExpr(s, rhs, fileImports, imports)
		}
	case *ast.ExprStmt:
		g.writeGoExpr(s, st.X, fileImports, imports)
	case *ast.IncDecStmt:
		g.writeGoExpr(s, st.X, fileImports, imports)
		s.WriteString(st.Tok.String())
	case *ast.SendStmt:
		g.writeGoExpr(s, st.Chan, fileImports, imports)
		s.WriteString(" <- ")
		g.writeGoExpr(s, st.Value, fileImports, imports)
	}
}

// writeGoComment writes a Go comment group with an optional indent prefix.
func writeGoComment(s *strings.Builder, cg *ast.CommentGroup, indent string) {
	for _, c := range cg.List {
		s.WriteString(indent)
		s.WriteString(c.Text)
		s.WriteString("\n")
	}
}
